//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AccessLog : IEntity
    {
        [Key]
        public int LogId { get; set; }
        public int UserId { get; set; }
        public System.DateTime ServerDateTime { get; set; }
        public string HostName { get; set; }
        public string ServerIP { get; set; }
        public string ClientIP { get; set; }
        public string MacAddress { get; set; }
        public int EventType { get; set; }
        public string EventDesc { get; set; }
        public string EventStatus { get; set; }
        public string FailureReason { get; set; }
        public string LogoutType { get; set; }
        public int SessionId { get; set; }
    }
}
