//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu : IEntity
    {
        public int mainMenuId { get; set; }
        public string mainMenuTextId { get; set; }
        public string mainMenuDescription { get; set; }
        public int mainMenuOrder { get; set; }
        public string mainMenuIcon { get; set; }
    }
}
