//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile : IEntity
    {
        public int profileId { get; set; }
        public string profileTextId { get; set; }
        public string profileDescription { get; set; }
        public string profileStatus { get; set; }
        public System.DateTime updatedDatetime { get; set; }
    }
}
