//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PWControlSetting : IEntity
    {
        [Key]
        public int CtrlSettingId { get; set; }
        public string TextId { get; set; }
        public string Description { get; set; }
        public int Value { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public Nullable<int> InsertedUserId { get; set; }
    }
}
