//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PWHistory : IEntity
    {
        [Key]
        public int HistoryId { get; set; }
        public System.DateTime ChangedDatetime { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public int UserId { get; set; }
    }
}
