//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu : IEntity
    {
        public int subMenuId { get; set; }
        public string subMenuTextId { get; set; }
        public string subMenuDescription { get; set; }
        public string subMenuOrder { get; set; }
        public string subMenuIcon { get; set; }
        public int mainMenuId { get; set; }
    }
}
