//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog : IEntity
    {
        public int userActivityLogId { get; set; }
        public string module { get; set; }
        public string action { get; set; }
        public string remark { get; set; }
        public System.DateTime insertedDatetime { get; set; }
        public int userId { get; set; }
    }
}
