//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.UserManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VwFeature : IEntity
    {
        [Key]
        public int profileFeatureId { get; set; }
        public string featureAction { get; set; }
        public string featureController { get; set; }
        public string featureDescription { get; set; }
        public Nullable<int> mainMenuId { get; set; }
        public Nullable<int> subMenuId { get; set; }
        public int profileId { get; set; }
        public string profileDescription { get; set; }
        public int featureId { get; set; }
        public string profileFeatureStatus { get; set; }
        public string featureTextId { get; set; }
    }
}
