//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azbil.Billing.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BILLINGDB : DbContext
    {
        public BILLINGDB()
            : base("name=BILLINGDB")
        {
        }
        public BILLINGDB(string connectionString) : base(connectionString) { }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppDbConfig> AppDbConfigs { get; set; }
        public virtual DbSet<ADLTariff> ADLTariffs { get; set; }
        public virtual DbSet<CPI> CPIs { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<MinOffTakeBase> MinOffTakeBases { get; set; }
        public virtual DbSet<SubsidiaryVariableValue> SubsidiaryVariableValues { get; set; }
        public virtual DbSet<VariableCondition> VariableConditions { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<ElectricityType> ElectricityTypes { get; set; }
        public virtual DbSet<WaterType> WaterTypes { get; set; }
        public virtual DbSet<BillingUnit> BillingUnits { get; set; }
        public virtual DbSet<ADLRecord> ADLRecords { get; set; }
        public virtual DbSet<MinOffTake> MinOffTakes { get; set; }
        public virtual DbSet<MonthlyBillSummaryStatus> MonthlyBillSummaryStatus1 { get; set; }
        public virtual DbSet<CSVFieldConfig> CSVFieldConfigs { get; set; }
        public virtual DbSet<SAPConfig> SAPConfigs { get; set; }
        public virtual DbSet<GeneralRate> GeneralRates { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<FormulaType> FormulaTypes { get; set; }
        public virtual DbSet<InvoiceConfig> InvoiceConfigs { get; set; }
        public virtual DbSet<FixedDemandCharge> FixedDemandCharges { get; set; }
        public virtual DbSet<TariffRecord> TariffRecords { get; set; }
        public virtual DbSet<VariableValue> VariableValues { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<GeneralConfig> GeneralConfigs { get; set; }
        public virtual DbSet<TariffRecordStatu> TariffRecordStatus { get; set; }
        public virtual DbSet<PlantVariable> PlantVariables { get; set; }
        public virtual DbSet<WaterRecord> WaterRecords { get; set; }
        public virtual DbSet<ElectricRecord> ElectricRecords { get; set; }
        public virtual DbSet<PQ> PQs { get; set; }
        public virtual DbSet<PQStatusHistory> PQStatusHistories { get; set; }
        public virtual DbSet<PQSubsidiaryVariable> PQSubsidiaryVariables { get; set; }
        public virtual DbSet<PSummary> PSummaries { get; set; }
        public virtual DbSet<MailNotifiConfig> MailNotifiConfigs { get; set; }
        public virtual DbSet<MailNotifiMonthlyBillSummary> MailNotifiMonthlyBillSummaries { get; set; }
        public virtual DbSet<ReDeclarationDemand> ReDeclarationDemands { get; set; }
        public virtual DbSet<BillingUnitFormula> BillingUnitFormulas { get; set; }
        public virtual DbSet<PSummaryStatu> PSummaryStatus { get; set; }
        public virtual DbSet<QSummaryStatu> QSummaryStatus { get; set; }
        public virtual DbSet<QSummary> QSummaries { get; set; }
        public virtual DbSet<MonthlyBillSummary> MonthlyBillSummaries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<BillingUnitConfig> BillingUnitConfigs { get; set; }
        public virtual DbSet<MinOffTakeRecordStatu> MinOffTakeRecordStatus { get; set; }
        public virtual DbSet<ElectricWaterTariff> ElectricWaterTariffs { get; set; }
        public virtual DbSet<QuarterCount> QuarterCounts { get; set; }
        public virtual DbSet<MailNotificationHistory> MailNotificationHistories { get; set; }
    }
}
