//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricWaterTariff : IEntity
    {
        public int ElectricWaterTariffId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public double Electric { get; set; }
        public Nullable<double> ElectricPeak { get; set; }
        public Nullable<double> ElectricOffPeak { get; set; }
        public double Water { get; set; }
        public double ECCCn { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public int InsertedUserId { get; set; }
        public double ElectricOP { get; set; }
    }
}
