//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinOffTake : IEntity
    {
        public int MinOffTakeId { get; set; }
        public int BillingUnitId { get; set; }
        public int MinOffTakeBaseId { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public Nullable<int> DDL { get; set; }
        public Nullable<double> DDLPercentage { get; set; }
        public Nullable<int> DIL { get; set; }
        public Nullable<double> DILPercentage { get; set; }
        public Nullable<double> DUH { get; set; }
        public Nullable<double> DUHPercentage { get; set; }
        public double MinOffTakeValue { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public int InsertedUserId { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Status { get; set; }
    }
}
