//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterCount : IEntity
    {
        public int QuarterCountId { get; set; }
        public int BillingUnitId { get; set; }
        public int Year { get; set; }
        public int Quarter { get; set; }
        public int NValue { get; set; }
    }
}
