//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDbConfig : IEntity
    {
        public int AppDbConfigId { get; set; }
        public string AppTextID { get; set; }
        public string DataSource { get; set; }
        public string DataBaseName { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
    }
}
