//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingUnitFormula : IEntity
    {
        public int BillingUnitFormulaId { get; set; }
        public int BillingUnitId { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public int FormulaTypeId { get; set; }
        public string Category { get; set; }
        public int InsertedUserId { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public string Status { get; set; }
    }
}
