//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricRecord : IEntity
    {
        public int ElectricRecordId { get; set; }
        public int PlantId { get; set; }
        public int ElectricityTypeId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public double ElecTariff { get; set; }
        public double PeakValue { get; set; }
        public double OffPeakValue { get; set; }
        public double PeakValueFac { get; set; }
        public double OffPeakValueFac { get; set; }
        public double PeakAvg { get; set; }
        public double OffPeakAvg { get; set; }
        public double PeakOffPeakAvg { get; set; }
        
    }
}
