//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MailNotifiMonthlyBillSummary : IEntity
    {
        [Key]
        public int MailBillSummaryId { get; set; }
        public int MonthlyBillSummaryId { get; set; }
        public int BillingUnitId { get; set; }
        public System.DateTime BillingDate { get; set; }
        public string MonthlyBillSummaryStatus { get; set; }
        public int MailID { get; set; }
        public string MailBillSummaryStatus { get; set; }
    }
}
