//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MailNotifiConfig : IEntity
    {
        [Key]
        public int MailConfigId { get; set; }
        public string ContextTextId { get; set; }
        public string Subject { get; set; }
        public string Header { get; set; }
        public string MailContentTemplate { get; set; }
        public string Footer { get; set; }
        public string Status { get; set; }
        public string CCRecipientAddressList { get; set; }
        public int Frequency { get; set; }
    }
}
