//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MailNotificationHistory : IEntity
    {
        [Key]
        public int MailID { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public string Subject { get; set; }
        public string ContextTextId { get; set; }
        public string MailBody { get; set; }
        public string SenderMailAddress { get; set; }
        public string RecieverMailAddress { get; set; }
        public int InsertedUserId { get; set; }
        public string Status { get; set; }
        public string CCRecipientAddress { get; set; }
    }
}
