//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBillSummary : IEntity
    {
        public int MonthlyBillSummaryId { get; set; }
        public int BillingUnitId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public double StartValue { get; set; }
        public double EndValue { get; set; }
        public double DCQuantity { get; set; }
        public double ECQuantity { get; set; }
        public double ActualECValue { get; set; }
        public Nullable<double> MinOfftakeShortFall { get; set; }
        public Nullable<double> MinOfftakeCharge { get; set; }
        public double DCRate { get; set; }
        public double ECRate { get; set; }
        public Nullable<double> ADLMaxPeekValue { get; set; }
        public Nullable<double> MaxPeak1 { get; set; }
        public Nullable<double> MaxPeak2 { get; set; }
        public Nullable<System.DateTime> MaxPeakStart1 { get; set; }
        public Nullable<System.DateTime> MaxPeakStart2 { get; set; }
        public Nullable<double> ADLQuantity { get; set; }
        public Nullable<double> ADLRate { get; set; }
        public Nullable<double> ADLUnitPrice { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public int InsertUserId { get; set; }
        public string Status { get; set; }
        public string DocumentNo { get; set; }
        public double GSTRate { get; set; }
        public double SpikeValue1 { get; set; }
        public Nullable<System.DateTime> SpikeTime1 { get; set; }
        public double SpikeValue2 { get; set; }
        public Nullable<System.DateTime> SpikeTime2 { get; set; }
        public Nullable<double> PerDayConsuption { get; set; }
        public string catergory { get; set; }
        public Nullable<System.DateTime> BillToDate { get; set; }
        public Nullable<double> DCRateEstimate { get; set; }
        public Nullable<double> ECRateEstimate { get; set; }
        public Nullable<double> ECStartValueEstimate { get; set; }
        public Nullable<double> ECEndValueEstimate { get; set; }
        public Nullable<double> ECSum { get; set; }
    }
}
