//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReDeclarationDemand : IEntity
    {
        public int ReDeclarationDemandId { get; set; }
        public int BillingUnitId { get; set; }
        public int DDL { get; set; }
        public int DIL { get; set; }
        public int Year { get; set; }
        public int YearHalf { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public int InsertedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
    }
}
