//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterRecord : IEntity
    {
        public int WaterRecordId { get; set; }
        public int PlantId { get; set; }
        public int WaterTypeId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public double WaterTariff { get; set; }
        public double WaterAvg { get; set; }
    }
}
