//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.EnergyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_summary : IEntity
    {
        public System.DateTime MONTH { get; set; }
        public long BLOCK_ID { get; set; }
        public long CS_ID { get; set; }
        public Nullable<double> C_START { get; set; }
        public Nullable<double> C_END { get; set; }
        public Nullable<float> C_TOTAL { get; set; }
        public Nullable<System.DateTime> C_ADL1_START { get; set; }
        public Nullable<System.DateTime> C_ADL1_END { get; set; }
        public Nullable<float> C_ADL1_DURATION { get; set; }
        public Nullable<float> C_ADL1_START_VALUE { get; set; }
        public Nullable<float> C_ADL1_PEAK_VALUE { get; set; }
        public Nullable<float> C_ADL1_END_VALUE { get; set; }
        public Nullable<System.DateTime> C_ADL2_START { get; set; }
        public Nullable<System.DateTime> C_ADL2_END { get; set; }
        public Nullable<float> C_ADL2_DURATION { get; set; }
        public Nullable<float> C_ADL2_START_VALUE { get; set; }
        public Nullable<float> C_ADL2_PEAK_VALUE { get; set; }
        public Nullable<float> C_ADL2_END_VALUE { get; set; }
        public Nullable<float> C_SPIKE1_VALUE { get; set; }
        public Nullable<System.DateTime> C_SPIKE1_TIME { get; set; }
        public Nullable<float> C_SPIKE2_VALUE { get; set; }
        public Nullable<System.DateTime> C_SPIKE2_TIME { get; set; }
        public Nullable<double> H_START { get; set; }
        public Nullable<double> H_END { get; set; }
        public Nullable<float> H_TOTAL { get; set; }
        public Nullable<System.DateTime> H_ADL1_START { get; set; }
        public Nullable<System.DateTime> H_ADL1_END { get; set; }
        public Nullable<float> H_ADL1_DURATION { get; set; }
        public Nullable<float> H_ADL1_START_VALUE { get; set; }
        public Nullable<float> H_ADL1_PEAK_VALUE { get; set; }
        public Nullable<float> H_ADL1_END_VALUE { get; set; }
        public Nullable<System.DateTime> H_ADL2_START { get; set; }
        public Nullable<System.DateTime> H_ADL2_END { get; set; }
        public Nullable<float> H_ADL2_DURATION { get; set; }
        public Nullable<float> H_ADL2_START_VALUE { get; set; }
        public Nullable<float> H_ADL2_PEAK_VALUE { get; set; }
        public Nullable<float> H_ADL2_END_VALUE { get; set; }
        public Nullable<float> H_SPIKE1_VALUE { get; set; }
        public Nullable<System.DateTime> H_SPIKE1_TIME { get; set; }
        public Nullable<float> H_SPIKE2_VALUE { get; set; }
        public Nullable<System.DateTime> H_SPIKE2_TIME { get; set; }
        public Nullable<System.DateTime> TIME_CALC { get; set; }
        public Nullable<float> C_DDL { get; set; }
        public Nullable<float> H_DDL { get; set; }
        public Nullable<float> C_DIL { get; set; }
        public Nullable<float> H_DIL { get; set; }
    }
}
