//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// imports IEntity interface 
using Azbil.Billing.Entities.Interfaces;

namespace Azbil.Billing.Entities.EnergyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_summary_cooling : IEntity
    {
        public System.DateTime DATE { get; set; }
        public long BLK_ID { get; set; }
        public long CS_ID { get; set; }
        public Nullable<double> START_RTH { get; set; }
        public Nullable<double> END_RTH { get; set; }
        public Nullable<float> TOTAL_RTH { get; set; }
        public Nullable<System.DateTime> SPIKE_TIME_1 { get; set; }
        public Nullable<float> SPIKE_1 { get; set; }
        public Nullable<System.DateTime> SPIKE_TIME_2 { get; set; }
        public Nullable<float> SPIKE_2 { get; set; }
        public Nullable<System.DateTime> ADL_START_1 { get; set; }
        public Nullable<System.DateTime> ADL_END_1 { get; set; }
        public Nullable<float> ADL_DURATION_1 { get; set; }
        public Nullable<float> ADL_START_VALUE_1 { get; set; }
        public Nullable<float> ADL_PEAK_VALUE_1 { get; set; }
        public Nullable<float> ADL_END_VALUE_1 { get; set; }
        public Nullable<System.DateTime> ADL_START_2 { get; set; }
        public Nullable<System.DateTime> ADL_END_2 { get; set; }
        public Nullable<float> ADL_DURATION_2 { get; set; }
        public Nullable<float> ADL_START_VALUE_2 { get; set; }
        public Nullable<float> ADL_PEAK_VALUE_2 { get; set; }
        public Nullable<float> ADL_END_VALUE_2 { get; set; }
        public Nullable<float> DDL { get; set; }
        public Nullable<float> DIL { get; set; }
    }
}
